export const TILE_SIZE = 32;
export const VIEWPORT_TILE_WIDTH = 25;
export const VIEWPORT_TILE_HEIGHT = 16;
export const VIEWPORT_TILE_RADIUS_X = Math.floor(VIEWPORT_TILE_WIDTH / 2);
export const VIEWPORT_TILE_RADIUS_Y = Math.floor(VIEWPORT_TILE_HEIGHT / 2);
export const VIEWPORT_TILE_RADIUS = VIEWPORT_TILE_RADIUS_X;
export const VIEWPORT_PIXEL_WIDTH = VIEWPORT_TILE_WIDTH * TILE_SIZE;
export const VIEWPORT_PIXEL_HEIGHT = VIEWPORT_TILE_HEIGHT * TILE_SIZE;
